version: "3.9"
services:
  web:
    image: node:18-alpine
    ports:
      - "3000:5173"
    volumes:
      - ../:/app
      - /app/node_modules/
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: sh -c "cd /app; npm install; npm run dev -- --host"
