version: "3.9"
services:
  web:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
